### ISSUE TITLE
conflict with better end

### ISSUE THREAD

**Issue by ChristsRisen** [SolipIngen/minecraft.armorrestitched#57]
version. 1.1.3 1.20.1 Fabric
using modrinth

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2024-05-28 06:32:15
Description: Exception ticking world

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1324.method_6192(double)" because the return value of "net.minecraft.class_1621.method_5996(net.minecraft.class_1320)" is null
	at net.minecraft.class_1621.handler$bej000$armorrestitched$injectedSetSize(class_1621.java:532)
	at net.minecraft.class_1621.method_7161(class_1621.java:101)
	at net.minecraft.class_1621.method_5943(class_1621.java:350)
	at org.betterx.betterend.entity.EndSlimeEntity.method_5943(EndSlimeEntity.java:97)
	at net.minecraft.class_1948.method_24930(class_1948.java:296)
	at net.minecraft.class_1948.method_8663(class_1948.java:213)
	at net.minecraft.class_1948.method_27821(class_1948.java:201)
	at net.minecraft.class_3215.method_14161(class_3215.java:379)
	at net.minecraft.class_3215.method_12127(class_3215.java:326)
	at net.minecraft.class_3218.method_18765(class_3218.java:333)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Unknown Source)

teaching myself to solve issues. tried to add endslime into the .jar but did not know the language. i solved the issue causing, exception world ticking, by disabling endslime in better end config. AR has no config so was unable to do anything else. i could be wrong but it seems like it was trying to add armor to the endslime. idk. just hoping the info will help someone less ignorant to fix the conflict. thanks.

**Comment by SolipIngen** [comment]
Hello, thank you for writing in.
This issue should have been fixed with the most recent 1.1.6-1.20.6 update. Please feel free to submit another issue should this persist.
